FROM mcr.microsoft.com/playwright:v1.52.0-noble

WORKDIR /app
ENV NODE_ENV=production
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

COPY package.json package-lock.json tsconfig.json ./
COPY config ./config
COPY src ./src
COPY tests ./tests

CMD ["node", "--experimental-strip-types", "src/cli.ts", "--help"]
